# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Auto Crawler

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: Linux
    strategy:
      matrix:
        python-version: [3.7]
    

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Chromdriver
      run: |
        if ![ -e 'chromedriver']; then
          echo 'chromedriver not exist!'
          sudo apt-get install google-chrome-stable
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.170/linux64/chromedriver-linux64.zip
          unzip ./chromedriver_linux64.zip
          rm -rf ./chromedriver_linux64.zip
        else
          echo 'chromedriver already exist!'
        fi
    - name: Add to PATH
      run: |
        echo "$(pwd)" >> $GITHUB_PATH
        echo $PATH
    - name: Run Crawler
      run: |
        python danawa_crawler.py
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
    - name: Commits
      run: |
       # remote가 존재하는지 확인
        if git remote | grep target > /dev/null; then
          git remote remove target
        fi

        git remote add target https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/ray5273/Danawa-Crawler.git
        git fetch
        git branch -r
        git checkout -b crawling-data/test origin/crawling-data/test
        
        git config --local user.email "ray5273@naver.com"
        git config --local user.name "Auto_Crawler_Bot"
        git add --all
        git commit -m "Bot - Auto Crawl | $(date -d '+9 hour' +'%Y-%m-%d %H:%M:%S')"
    - name: Push
      run: |
        git config --global user.name "Auto_crawler_bot"
        git config --global user.email "ray5273@naver.com"
        git push target crawling-data/test
